### ISSUE TITLE
Code-Review

### ISSUE THREAD

**Issue by qwibbler** [qwibbler/Capstone-Js-and-Networking#22]
### Project:
https://github.com/qwibbler/Capstone-Js-and-Networking

### 2 Person Team:
- @ivaan1992
- @qwibbler

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this task! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Required Changes ♻️
_Kindly check the comments under the review._
- [x] There are unassigned cards in your board. Kindly ensure that **all** cards are assigned to team members. You should see a circle with user's avatar on each card. See the example below:

![image](https://user-images.githubusercontent.com/12745474/146837343-f7894d44-f129-4e6e-ad2c-f88f48cee8bf.png)

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
